id: P000573
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:47:44.186357
source_metadata:
  id: bdr:W1KG25755
  title: སྙན་ངག་ལས་འཕྲོས་པའི་མཚུངས་སྒྲའི་དཔྱད་པ།
  author: ''
  volumes:
    8c935e7da27445ca97e11081448367c8:
      image_group_id: I1KG25757
      title: Volume 1 of snyan ngag las 'phros pa'i mtshungs sgra'i dpyad pa/
      volume_number: 1
      total_pages: 213
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
