id: I414A040A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:48:39+00:00'
last_modified: '2022-06-07T12:21:36.619064+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25755
  title: སྙན་ངག་ལས་འཕྲོས་པའི་མཚུངས་སྒྲའི་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    AD2D:
      image_group_id: I1KG25757
      title: Volume 1 of snyan ngag las 'phros pa'i mtshungs sgra'i dpyad pa/
      total_pages: 213
      order: 1
      base_file: AD2D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
